version: '3.8'

services:
  db:
    restart: always
    ports: []

  backend:
    restart: always
    ports: []

  frontend:
    restart: always
    ports: []

  prometheus:
    restart: always
    ports: []

  grafana:
    restart: always

  nginx:
    restart: always
